googledocs:
    username: username@gmail.com
    password: password

saaspose:
    appSID: theappSID
    appKey: theappKey
    
doxument:
    apiKey: theappKey
    apiToken: theappToken
    
livedocx:
    username: username
    password: password